[package]
name = "asm_sim"
version = "0.1.0"
authors = ["JLockerman <joshua@lockerman.info>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
